sudo: required

dist: xenial

language: python

virtualenv:
#  system_site_packages: true
  
python:
- '3.6'
- 3.6-dev
- '3.7'
- 3.7-dev
- 3.8-dev
- nightly

before_install:
- sudo apt-get install -y agda-mode

install:
- pip install -r requirements.txt

script:
- pip install .
- make test

notifications:
  email: false
   
after_script: cd ~

deploy:
  provider: pypi
  user: "lorenzo"
  password:
  secure: "uLJYrcy5iL2VpzdiAYrENu33M3uA4kRIkKi7ndg79lhX3PcyaPhgqewnZq/a7aJjaKICNh6tzK4IDRLy50QH1uY7ovHA30mGmYeOGZUNoGdeddEkVp3q42YPVNQ32EL+xYYDlBjRH7rQXwQ2Ft+pOG7dMrLf7OKJswPGFk+9VmFQHBK/nWX03RMGETvDC7DO+W6w+wlNck/R8VV4FTf7VXKFzFfmhVt3YejFING5SuyysGRDTLmpGdcCMYnM6jxSOVgvu81Q9kFZnygTZzA/g96a/pKcvYgyEyFZnqaYUHODTZqo+r9wEdz+7ZX1CpNc/8Kv7o92WzB36XeCyXQ5OH4VZ4oo5wwOCWNcjMJonaHlIE5eiBLiHt5LIRcYIm3YrtAz7rxxaDfw1D08ELCksKrn2xAeCQYSCnAdAkow96DB/4TXF5KT2Xl2LFyFEKKWqyuKMXBrRLwuOV0t4oeZZ+3IqESbqme8h+ZER/wlDx+h0JH3wtJOWJ423K6GGIz0ZekGMlsITvMrvQIB+EPVOiIflxdQHZE1iOi1DSALPnmrUNaTeO64f6bN+1/eAONSmDnvEYZD9BbIAwASqFYAucQWjklk5PHdDzoHsLxe+XlqFXm/ehSAgJSt82sY/ethFFZoI2zUsv0QHP3/r0SdgdwA/1YA318ls3PH6EhxL2Y="
