name: example-environment
channels:
  - conda-forge
dependencies:
  - python
#  - numpy
  - pip
  - pip:
    - git+https://github.com/lclem/jupyter_contrib_nbextensions
    - jupyterthemes
    - agda_kernel

#before_script:
  #- sudo apt-add-repository ppa:swi-prolog/stable -y
  #- sudo apt-get update -q
  #- sudo apt-get install swi-prolog

script:
  - make test
