#!/bin/bash

make local-install
make kernel-install
make codemirror-install

#sudo apt-get install agda-mode
#sudo apt-get install agda-stdlib

#pip install agda_kernel

#cabal update
#cabal install Agda
#agda-mode setup

jupyter contrib nbextension install --user
jupyter nbextension enable --py widgetsnbextension
jupyter nbextension enable agda-extension/main
jupyter nbextension enable literate-markdown/main
jupyter nbextension enable toc2/main
jupyter nbextension enable hide_input/main
jupyter nbextension enable init_cell/main
jupyter nbextension enable freeze/main
