#!/bin/bash

make local-install
make kernel-install
make codemirror-install

sudo apt-get install agda-mode
sudo apt-get install agda-stdlib

#pip install agda_kernel

#cabal update
#cabal install Agda
#agda-mode setup
